apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - dashy.yaml
configMapGenerator:
  - name: dashy-config
    files:
      - conf.yml
configurations:
  - kustomizeconfig.yaml
