controllers:
  main:
    type: statefulset
    pod:
      nodeSelector:
        zwave: "true"
    containers:
      main:
        image:
          repository: zwavejs/zwave-js-ui
          tag: latest
        securityContext:
          privileged: true

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 8091
      api:
        port: 3000

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /root/container-data/zwave-ui
    globalMounts:
      - path: /usr/src/app/store

  zwave-device:
    enabled: true
    type: hostPath
    hostPath: /dev/serial/by-id/usb-1a86_USB_Single_Serial_58E3038596-if00
    globalMounts:
      - path: /dev/zwave
