controllers:
  main:
    pod:
      hostPID: true
    containers:
      main:
        image:
          repository: nicolargo/glances
          tag: latest
        env:
          GLANCES_OPT: "-w"
          TZ: "America/Los_Angeles"
        securityContext:
          privileged: true

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 61208

ingress:
  main:
    enabled: true
    hosts:
      - host: glances.trevorpi.lan
        paths:
          - path: /
            pathType: Prefix
