controllers:
  main:
    containers:
      main:
        image:
          repository: nicolargo/glances
          tag: latest
        env:
          GLANCES_OPT: "-w"
          TZ: "America/Los_Angeles"
        securityContext:
          privileged: true

hostPID: true

service:
  main:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: 61208
